Repository openclimatefix/Satip, pull requests merged in 2022-01, with the labels that each got.

#49 Add support for Data Tailor
  satip/eumetsat.py
  satip/geospatial.py
  satip/intermediate.py
  satip/utils.py
  scripts/convert_cloudmask_to_zarr.py
  scripts/convert_native_to_zarr.py
Labels: enhancement

#51 Add plotting to CI
  .github/workflows/plotting.yaml
  satip/eumetsat.py
  satip/utils.py
  scripts/generate_test_plots.py
  tests/test_eumetsat.py
Labels: enhancement

#56 Fix coordinates
  .flake8
  satip/compression.py
  satip/geospatial.py
  satip/serialize.py
  satip/utils.py
Labels: bug

#60 Add only calculating OSGB coordinates once
  satip/intermediate.py
  satip/utils.py
Labels: enhancement

#63 Rename coordinates to be more explicit
  satip/compression.py
  satip/utils.py
Labels: enhancement

#64 Add saving attributes for all channels
  satip/utils.py
Labels: enhancement

#53 added environment.yml and updated README with conda instructions
  README.md
  environment.yml
  setup.py
Labels: documentation, enhancement
